version: 2

updates:
  - package-ecosystem: npm
    target-branch: "v0.1.0-prep"
    directory: "/api"
    schedule:
      interval: live
    open-pull-requests-limit: 30

  - package-ecosystem: npm
    target-branch: "v0.1.0-prep"
    directory: "/frontend"
    schedule:
      interval: live
    open-pull-requests-limit: 30