version: 2

updates:
  - package-ecosystem: npm
    directory: "/api"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    target_branch: "v0.1.0-prep"

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    target_branch: "v0.1.0-prep"