version: 2

updates:
  - package-ecosystem: npm
    target-branch: "v0.2.0-prep"
    directory: "/api"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    default_reviewers:
      - "sethlessard"

  - package-ecosystem: npm
    target-branch: "v0.2.0-prep"
    directory: "/frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    default_reviewers:
      - "sethlessard"
