FROM node:14

COPY . /do-dydns

WORKDIR /do-dydns/api
RUN npm install
RUN npm install -g mocha chai

WORKDIR /do-dydns/frontend
RUN npm install

WORKDIR /do-dydns

EXPOSE 9229
EXPOSE 3000
EXPOSE 3080

RUN ls

RUN chmod +x ./docker/start-do-dydns-dev.sh

CMD ./docker/start-do-dydns-dev.sh
