FROM node:12

RUN npm install -g mocha chai

RUN mkdir -p /do-dydns/api
RUN mkdir -p /do-dydns/frontend
RUN mkdir -p /do-dydns/scripts

WORKDIR /do-dydns

# install the api dependencie
WORKDIR /do-dydns/api
COPY ./api/package.json package.json
RUN npm install

# install the frontend dependencies
WORKDIR /do-dydns/frontend
COPY ./frontend/package.json package.json
RUN npm install

WORKDIR /do-dydns
RUN ls

# expose the ports
EXPOSE 9229
EXPOSE 3000
EXPOSE 3080

# copy the applicatio
COPY ./api/ /do-dydns/api
COPY ./frontend/ /do-dydns/frontend
COPY ./scripts/start-do-dydns-dev.sh .

RUN chmod +x ./start-do-dydns-dev.sh

CMD ./start-do-dydns-dev.sh
