version: "2.3"
services:
  api:
    build:
      context: ./api/
      dockerfile: ../docker/api.Dockerfile.prod
    ports:
      - "3080:3080"
    # TODO: setup data volume
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.Dockerfile.prod
    ports:
      - "9090:80"
    stdin_open: true
