version: "2.3"
services:
  api:
    build:
      context: ./api/
      dockerfile: ../docker/api.Dockerfile.prod
    ports:
      - "3080:3080"
    environment:
      - PORT=3080
      - HOST=0.0.0.0
    volumes:
        - data:/do-dydns/api
    restart: "unless-stopped"
  frontend:
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.Dockerfile.prod
    ports:
      - "9090:80"
    stdin_open: true
    restart: "unless-stopped"

volumes:
  data:
    driver: local    
