FROM node:12

RUN npm install -g mocha chai

WORKDIR /do-dydns/api
ADD /api/package.json .
ADD /api/package-lock.json .
RUN npm install

WORKDIR /do-dydns/frontend
ADD /frontend/package.json .
ADD /frontend/package-lock.json .
RUN npm install

WORKDIR /do-dydns

EXPOSE 9229
EXPOSE 3000
EXPOSE 3080

ADD /api/ /do-dydns/api
ADD /frontend/ /do-dydns/frontend
ADD /scripts/start-do-dydns-dev.sh .

RUN chmod +x ./start-do-dydns-dev.sh

CMD ./start-do-dydns-dev.sh
